/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 课程表文章标签类型, 目前不多选,
 * 
 */
public enum ArticleLabelType implements org.apache.thrift.TEnum {
  ArticleLabelType_Policy(1),
  ArticleLabelType_Courseware(2),
  ArticleLabelType_Notification(3);

  private final int value;

  private ArticleLabelType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ArticleLabelType findByValue(int value) { 
    switch (value) {
      case 1:
        return ArticleLabelType_Policy;
      case 2:
        return ArticleLabelType_Courseware;
      case 3:
        return ArticleLabelType_Notification;
      default:
        return null;
    }
  }
}
