/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import org.apache.thrift.TEnum;

public enum ExamStatus implements TEnum {
  DNS(1),
  Start(2),
  Finish(3),
  DNF(4);

  private final int value;

  private ExamStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExamStatus findByValue(int value) {
    switch (value) {
      case 1:
        return DNS;
      case 2:
        return Start;
      case 3:
        return Finish;
      case 4:
        return DNF;
      default:
        return null;
    }
  }
}
