/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FileRelationType implements org.apache.thrift.TEnum {
  FileRelationType_Article(1),
  FileRelationType_Feedback(2);

  private final int value;

  private FileRelationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FileRelationType findByValue(int value) { 
    switch (value) {
      case 1:
        return FileRelationType_Article;
      case 2:
        return FileRelationType_Feedback;
      default:
        return null;
    }
  }
}
