/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PlatformType implements org.apache.thrift.TEnum {
  PlatformType_web(0),
  PlatformType_android(1),
  PlatformType_ios(2),
  PlatformType_windows(3);

  private final int value;

  private PlatformType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PlatformType findByValue(int value) { 
    switch (value) {
      case 0:
        return PlatformType_web;
      case 1:
        return PlatformType_android;
      case 2:
        return PlatformType_ios;
      case 3:
        return PlatformType_windows;
      default:
        return null;
    }
  }
}
