/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 推送类型PushType_Article
 * 
 */
public enum PushType implements org.apache.thrift.TEnum {
  PushType_Article(1),
  PushType_Message(2);

  private final int value;

  private PushType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PushType findByValue(int value) { 
    switch (value) {
      case 1:
        return PushType_Article;
      case 2:
        return PushType_Message;
      default:
        return null;
    }
  }
}
