/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserAuthStatus implements org.apache.thrift.TEnum {
  UserAuth_Normal(1),
  UserAuth_Ing(2),
  UserAuth_Failed(3),
  UserAuth_Success(4);

  private final int value;

  private UserAuthStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserAuthStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return UserAuth_Normal;
      case 2:
        return UserAuth_Ing;
      case 3:
        return UserAuth_Failed;
      case 4:
        return UserAuth_Success;
      default:
        return null;
    }
  }
}
