/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserStatus implements org.apache.thrift.TEnum {
  Default(0),
  Deleted(1),
  Online(2),
  Offline(3),
  Login(4),
  Logout(5);

  private final int value;

  private UserStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Default;
      case 1:
        return Deleted;
      case 2:
        return Online;
      case 3:
        return Offline;
      case 4:
        return Login;
      case 5:
        return Logout;
      default:
        return null;
    }
  }
}
